const availableScenes = [
  'simpleExample',
  'mouseExample',
  'textExample',
  'speechExample',
  'oscExample',
  'photoExample',
  'socket',
  'multipleusers',
  'speech',
  'body',
  'audienceMedia',
  'group1-music',
  'group1-background',
  'group1-lights',
];
